version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:aspire
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT:-http://aspire:18889}
      OTEL_EXPORTER_OTLP_PROTOCOL: ${OTEL_EXPORTER_OTLP_PROTOCOL:-grpc}

  aspire:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:latest
    restart: unless-stopped
    ports:
      - 18888:18888
      - 18889:18889
    environment:
      ASPIRE_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS : 'true'
